/* liquid fill js*/
var gauge1 = loadLiquidFillGauge('fillgauge1', 85);
    var config1 = liquidFillGaugeDefaultSettings();
    config1.circleColor = '#f53240';
    config1.textColor = '#f53240';
    config1.waveTextColor = '#fca1a8';
    config1.waveColor = '#f53240';
    config1.circleThickness = 0.06;
    config1.textVertPosition = 0.5;
    config1.waveAnimateTime = 1000;
    config1.waveHeight = 0.05;
    config1.waveAnimate = true;
    config1.waveRise = false;
    config1.waveHeightScaling = false;
    config1.waveOffset = 0.25;
    config1.waveCount = 2;
    var gauge2= loadLiquidFillGauge('fillgauge2', 50, config1);
    var config2 = liquidFillGaugeDefaultSettings();
    config2.circleColor = '#a4d555';
    config2.textColor = '#a4d555';
    config2.waveTextColor = '#defcae';
    config2.waveColor = '#a4d555';
    config2.circleThickness = 0.06;
    config2.textVertPosition = 0.5;
    config2.waveAnimateTime = 1000;
    config2.waveHeight = 0.05;
    config2.waveAnimate = true;
    config2.waveRise = false;
    config2.waveHeightScaling = false;
    config2.waveOffset = 0.25;
    config2.waveCount = 2;
    var gauge3 = loadLiquidFillGauge('fillgauge3', 40, config2);
    var config3 = liquidFillGaugeDefaultSettings();
    config3.circleColor = '#f9be02';
    config3.textColor = '#f9be02';
    config3.waveTextColor = '#fae49f';
    config3.waveColor = '#f9be02';
    config3.circleThickness = 0.06;
    config3.textVertPosition = 0.5;
    config3.waveAnimateTime = 1000;
    config3.waveHeight = 0.05;
    config3.waveAnimate = true;
    config3.waveRise = false;
    config3.waveHeightScaling = false;
    config3.waveOffset = 0.25;
    config3.waveCount = 2;
    var gauge4= loadLiquidFillGauge('fillgauge4', 95, config3);
    var config4 = liquidFillGaugeDefaultSettings();
    config4.circleColor = '#f53240';
    config4.textColor = '#f53240';
    config4.waveTextColor = '#fba6ac';
    config4.waveColor = '#f53240';
    config4.circleThickness = 0.06;
    config4.textVertPosition = 0.5;
    config4.waveAnimateTime = 1000;
    config4.waveHeight = 0.05;
    config4.waveAnimate = true;
    config4.waveRise = false;
    config4.waveHeightScaling = false;
    config4.waveOffset = 0.25;
    config4.waveCount = 2;
    var gauge5 = loadLiquidFillGauge('fillgauge5', 95, config4);
    var config5 = liquidFillGaugeDefaultSettings();
    config5.circleColor = '#a4d555';
    config5.textColor = '#a4d555';
    config5.waveTextColor = '#d8f8a4';
    config5.waveColor = '#a4d555';
    config5.circleThickness = 0.06;
    config5.textVertPosition = 0.5;
    config5.waveAnimateTime = 1000;
    config5.waveHeight = 0.05;
    config5.waveAnimate = true;
    config5.waveRise = false;
    config5.waveHeightScaling = false;
    config5.waveOffset = 0.25;
    config5.waveCount = 2;
    var gauge6= loadLiquidFillGauge('fillgauge6', 75, config5);
    var config6 = liquidFillGaugeDefaultSettings();
    config6.circleColor = '#6c6488';
    config6.textColor = '#6c6488';
    config6.waveTextColor = '#d5cafb';
    config6.waveColor = '#6c6488';
    config6.circleThickness = 0.06;
    config6.textVertPosition = 0.5;
    config6.waveAnimateTime = 1000;
    config6.waveHeight = 0.05;
    config6.waveAnimate = true;
    config6.waveRise = false;
    config6.waveHeightScaling = false;
    config6.waveOffset = 0.25;
    config6.waveCount = 2;
    var gauge7 = loadLiquidFillGauge('fillgauge7', 40, config6);
    var config7 = liquidFillGaugeDefaultSettings();
    config7.circleColor = '#f7882f';
    config7.textColor = '#f7882f';
    config7.waveTextColor = '#fed2af';
    config7.waveColor = '#f7882f';
    config7.circleThickness = 0.06;
    config7.textVertPosition = 0.5;
    config7.waveAnimateTime = 1000;
    config7.waveHeight = 0.05;
    config7.waveAnimate = true;
    config7.waveRise = false;
    config7.waveHeightScaling = false;
    config7.waveOffset = 0.25;
    config7.waveCount = 2;    var gauge8 = loadLiquidFillGauge('fillgauge8', 40, config7);
    var config8 = liquidFillGaugeDefaultSettings();
    config8.circleColor = '#02c8a7';
    config8.textColor = '#02c8a7';
    config8.waveTextColor = '#bcf5ec';
    config8.waveColor = '#02c8a7';
    config8.circleThickness = 0.06;
    config8.textVertPosition = 0.5;
    config8.waveAnimateTime = 1000;
    config8.waveHeight = 0.05;
    config8.waveAnimate = true;
    config8.waveRise = false;
    config8.waveHeightScaling = false;
    config8.waveOffset = 0.25;
    config8.waveCount = 2;
/*page pilling js*/
    		var deleteLog = false;
		$(document).ready(function() {
	    	$('#pagepiling').pagepiling({
	    		menu: '#menu',
	    		anchors: ['page1', 'page7', 'page2','page5', 'page3','page6', 'page4'],
			    sectionsColor: ['#f53240','#f53240', '#7cdbd5','#7cdbd5', '#f9be02','#f9be02', '#a4d555'],
			    loopTop: true,
			    loopBottom: true
			});
	    });


